### PR TITLE
Fix request

### PR DESCRIPTION
**Pull request by yllen**
No items in list

### CODE REVIEW

**Review by btry — APPROVED** [review]

**Comment by btry** [comment]
Hi

Can you rebase the patch for merge into develop instead of master ?

**Comment by yllen** [comment]
Rebase done

**Comment by btry** [comment]
Hi 

In the mean time I created #64 to make the plugin compatible with GLPI 9.2. I integrated your fix, and corrected the SQL ON clause which missed a closing parenthesis.

**Comment by btry** [comment]
fix corrected and merged in develop branch (develop becomes incompatible with GLPI 9.1.x due to fixed deprecations)

**Pull request closed without merging**
