### PR TITLE
Compatible with GLPI 9.3

### PR DESCRIPTION
**Pull request by staltrans**
Fix search options.
Fix deprecated methods.
Fix code style.

### CODE REVIEW

**Comment by btry** [comment]
Hi

The simcards are in GLPI core since the version 9.2.0. Why do you still need this plugin ?

**Comment by dgsn** [comment]
Because, SimCards are more than components. they must be attached to a contract. They have a PUK code, etc...
Best regards

**Comment by btry** [comment]
Hi
All specifities of the simcards are available in the version implemtned in the  core.

See this screenshot
https://user-images.githubusercontent.com/14139801/27424451-5ed64ec0-5735-11e7-95c9-35c9f839998a.png

extracted from the PR : https://github.com/glpi-project/glpi/pull/2311

Can you tell what is missing between the current implementation  and the plugin ?

EDIT : the screenshot misses an extra field, which was added a bit later.

Here is a screenshot of a simcard in GLPI 9.4.3
image

**Comment by dgsn** [comment]
Tickets and problems. Can we use file injection ?
But it is not the most important for me.
The way to manage this type of object is more complicated by components.
With the plugin i have directly a list of all the SimCards and i can work with a list of elements for updates.
Best regards

**Comment by btry** [comment]
As far as I know the data injection plugin was not updated to handle simcards as component. 

Associating the ticket or problem to the asset containing the component seems to me a better option. Except if associating a ticket to a simcard is needed when it is NOT associated to any asset. Feel free to open an issue in GLPI about that with a use case, if you need this.

Simcards are now splitted into 2 subsets of data, because this is the current design of components.  However, the plugin (if I remember well) provided a template for the simcards, which is quite close to the design of compoments where you create a component then fill its specs in an instance of this component. Consider you have several hard drives with the exact same model, and each instance has its own serial number.
About listin

all simcards instances in a single list is indeed not possible. You may anyway do a mass update of instances for a single type of simcard. Do you have such case where you need to update for example the status of simcards of different type (micro and mini size ) ?

**Comment by dgsn** [comment]
can we speak directly by phone (in french :-).
Some examples...
Actually, we are changing of provider and all the SimCards are replaced but the line number is the same.
We have a stock of empty SimCards to manage....
Etc...
Maybe a better way will be use GenericObject instead of plugin SimCards... 
I don't know.
Best regards

**Comment by cedric-anne** [comment]
Hi,

Looks like develop branch already contains 9.3 compatibility, so I close this PR.

Feel free to open a new PR if some fixes are missing.

Regards

**Pull request closed without merging**
